# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7861cbd9648a1380cdab67c9c3f2660c8ea9da69d345f0514508df7f701b3f3c651c48eda0257fe4ad85e3d377ae13f963328912111acbc8d009cba7241d5fd6

test:
  secret_key_base: 4a4bf6a99b55f1fbae382d48a528205338b6a7764fe16d49c8f860ec3e1836a4620e4873ee677583ccee5cd3a6b47e242acf6e71839159636ec6d556b260ac05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
